---
title: Pivotal Cloud Foundry Metrics Release Notes
owner: Metrix
---

## Version 1.0.4

## Known Issues
* Route mappings for metrics.<system_domain> and metrics.<system_domain>/v2 may be overwritten or incorrectly mapped during redeploys.
* For applications that do not have any activity in the past 24 hours (which means no app events or http requests have been generated), users will not see any data in the UI. They will also need to refresh their browser after metrics are generated by the use of the app.
* While installing the PCF Metrics tile, the default Resource Config settings for each resource pool may be over-sized for POC/Beta purposes. You may adjust them manually to fit your environment.
* No direct upgrade path. Operators can delete the installed tile and install the new tile.  This does result in downtime and data loss.

## Version 1.0.3

## Known Issues
* Not all applications metrics are accessible to admin users.
* For applications that do not have any activity in the past 24 hours (which means no app events or http requests have been generated), users will not see any data in the UI. They will also need to refresh their browser after metrics are generated by the use of the app.
* While installing the PCF Metrics tile, the default Resource Config settings for each resource pool may be over-sized for POC/Beta purposes. You may adjust them manually to fit your environment.
